
package ru.job4j.restservice.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BooksPort", targetNamespace = "http://libraryservice.job4j.ru/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BooksPort {


    /**
     * 
     * @param findBookByIdRequest
     * @return
     *     returns ru.job4j.restservice.wsdl.FindBookByIdResponse
     */
    @WebMethod
    @WebResult(name = "findBookByIdResponse", targetNamespace = "http://libraryservice.job4j.ru/ws", partName = "findBookByIdResponse")
    public FindBookByIdResponse findBookById(
        @WebParam(name = "findBookByIdRequest", targetNamespace = "http://libraryservice.job4j.ru/ws", partName = "findBookByIdRequest")
        FindBookByIdRequest findBookByIdRequest);

    /**
     * 
     * @param findAllBooksRequest
     * @return
     *     returns ru.job4j.restservice.wsdl.FindAllBooksResponse
     */
    @WebMethod
    @WebResult(name = "findAllBooksResponse", targetNamespace = "http://libraryservice.job4j.ru/ws", partName = "findAllBooksResponse")
    public FindAllBooksResponse findAllBooks(
        @WebParam(name = "findAllBooksRequest", targetNamespace = "http://libraryservice.job4j.ru/ws", partName = "findAllBooksRequest")
        FindAllBooksRequest findAllBooksRequest);

}
