
package ru.job4j.restservice.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CountriesPort", targetNamespace = "http://libraryservice.job4j.ru/model")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountriesPort {


    /**
     * 
     * @param getBookRequest
     * @return
     *     returns ru.job4j.restservice.wsdl.GetBookResponse
     */
    @WebMethod
    @WebResult(name = "getBookResponse", targetNamespace = "http://libraryservice.job4j.ru/model", partName = "getBookResponse")
    public GetBookResponse getBook(
        @WebParam(name = "getBookRequest", targetNamespace = "http://libraryservice.job4j.ru/model", partName = "getBookRequest")
        GetBookRequest getBookRequest);

}
