//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.28 at 09:11:41 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://libraryservice.job4j.ru/ws", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.job4j.libraryservice.ws;
