server:
  port: 8081

# Minio properties
minio:
  access:
    name: minioadmin
    secret: minioadmin
  bucket:
    name: images
  default:
    folder: images
  url: http://minio:9000

# Datasource properties
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: '{cipher}6c3d1d587ebe4c1b45359953900b4e7136bcbd838552484d5413076b735c6cd2'
    url: jdbc:postgresql://db:5432/library
    username: postgres
  kafka:
    bootstrap-servers: kafka:9092