server:
    port: 8081
management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'

# Eureka properties
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://eurekaserver:8070/eureka/
    instance:
        preferIpAddress: true

# Kafka variables
library-project:
    consumer-group: library-kafka-group
    reply-topics-all: library-topics-reply-all
    reply-topics-by-id: library-topics-reply-by-id
    send-topics-all: library-topics-all
    send-topics-by-id: library-topics-by-id

# Minio properties
minio:
    access:
        name: minioadmin
        secret: minioadmin
    bucket:
        name: images
    default:
        folder: images
    url: http://127.0.0.1:9000

# Datasource properties
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: '{cipher}6c3d1d587ebe4c1b45359953900b4e7136bcbd838552484d5413076b735c6cd2'
        url: jdbc:postgresql://127.0.0.1:5432/library
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                format_sql: true
        show-sql: false
    liquibase:
        change-log: classpath:liquibase-changeLog.xml
        enabled: true