server.port=8080

# Eureka properties
eureka.instance.preferIpAddress = true
eureka.client.registerWithEureka = true
eureka.client.fetchRegistry = true
eureka.client.serviceUrl.defaultZone = http://eurekaserver:8070/eureka/

# Kafka properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.group-id=app.lib.1